- name: Provision EC2
  hosts: ec2-instance  # Ganti ke nama host yang sesuai dengan inventory
  become: true
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install nginx
      apt:
        name: nginx
        state: present
