name: CI/CD for AWS Infra

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest
    #needs: terraform  # Pastikan job Ansible dijalankan setelah Terraform selesai

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Move to ansible directory
        run: cd ansible  #

      - name: Set up Ansible
        run: sudo apt-get install -y ansible

      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS credentials set"

      - name: Create Ansible inventory with manual IP
        run: |
          echo "[all]" > inventory_aws_ec2.yml
          echo "ec2-instance ansible_host=13.215.175.134 ansible_user=ec2-user ansible_ssh_private_key_file=pahmil.pem" >> inventory_aws_ec2.yml


      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory_aws_ec2.yml site.yml