name: CI/CD for AWS Infra

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=ap-southeast-1" >> $GITHUB_ENV  # Ganti dengan region yang sesuai
          
      - name: List files in the current directory
        run: ls -al

      - name: Move to terraform directory
        run: cd terraform  # Ganti 'terraform' dengan folder yang sesuai

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Initialize Terraform
        run: cd terraform && terraform init

      - name: Run Terraform Plan
        run: cd terraform && terraform plan

      - name: Apply Terraform
        run: cd terraform && terraform apply -auto-approve
      
      - name: Get EC2 public IP
        id: ec2_ip
        run: echo "::set-output name=ec2_ip::$(terraform output -raw ec2_public_ip)"
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        run: sudo apt-get install -y ansible

      - name: Set AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS credentials set"

      - name: Create Ansible inventory
        run: |
          echo "[all]" > inventory_aws_ec2.yml
          echo "ec2-instance ansible_host=${{ needs.terraform.outputs.ec2_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=pahmil.pem" >> inventory_aws_ec2.yml


      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory_aws_ec2.yml site.yml